name: my_personal_hero
description: Search for your favorite super heroes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  flutter_bloc: ^6.1.1
  flutter_svg: ^0.19.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  google_fonts: ^1.1.1
  http: ^0.12.2
  json_serializable: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  effective_dart: ^1.3.0
  freezed: ^0.12.6
  mockito: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
