name: my_personal_hero
description: Search for your favorite super heroes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  freezed_annotation: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11
  effective_dart: ^1.3.0
  freezed: ^0.12.6

flutter:
  uses-material-design: true
